Добавляет функцию format_post_date для форматирования даты в карточка…
htmlacademy-php/473761-readme-12 pull request #6
Opened 2021-05-13 17:47 UTC by danielvinogradov

…х постов

2021-05-14 15:11 UTC, ademaro requested changes
Давай сделаем поправки и двинем дальше

2021-05-14 15:11 UTC, ademaro commented on index.php
> +date_default_timezone_set('Europe/Moscow');
Думаю, можно подумать о файле с настройками

2021-05-14 15:11 UTC, ademaro commented on templates/main.php
> +        require_once('helpers.php');
Их же подключаем в контроллерах...

2021-05-14 15:11 UTC, ademaro commented on templates/main.php
> +        <?php foreach ($posts as $key => $post): ?>
key у нас в данном случае post_id? давай так и назовём

2021-05-14 15:11 UTC, ademaro commented on utils/format_post_date.php
> +require_once('helpers.php');
Напомни на консультации с подключением зависимостей, разберём подробнее

2021-05-14 15:11 UTC, ademaro commented on utils/format_post_date.php
> +        return "{$num} {$plural_form} назад";
Фигурные скобки не нужны, интерполяция переменных в двойных кавычках работает и так в php

2021-05-14 15:23 UTC, danielvinogradov commented
Изменения отправил. Про подключение зависимостей записал, на консультации напомню.

2021-05-16 15:27 UTC, ademaro approved these changes

2021-05-16 15:27 UTC, merged